[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "k8s.io/klog"
  version = "0.2.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.13.4"

[prune]
  go-tests = true
  unused-packages = true
